export const data = [
  {
    id: 1,
    title: "Armoir",
    price: "109.95",
    description: "Your perfect pack for everyday.",
    category: "Chambre",
    image: "/armoir.jpg",
    stars: "4",
  },
  {
    id: 2,
    title: "Meuble TV",
    price: "509.95",
    description: "Your perfect pack for everyday.",
    category: "Salon",
    image: "/meubleTV.jpg",
    stars: "3",
    option: [
      {
        color: "#444",
      },
    ],
  },
  {
    id: 3,
    title: "Canapé",
    price: "509.95",
    description: "Your perfect pack for everyday.",
    category: "Cusine",
    image: "canapéBlanc.jpg",
    stars: "2.5",
  },
  {
    id: 4,
    title: "Chaise",
    price: "300.99",
    description: "Your perfect pack for everyday.",
    category: "Cusine",
    image: "/chaise.jpg",
    stars: "4",
  },
  {
    id: 5,
    title: "Tapie",
    price: "200",
    description: "Your perfect pack for everyday.",
    category: "Cusine",
    image: "/tapie.jpg",
    stars: "2",
  },
  {
    id: 6,
    title: "Pouffe",
    price: "45.95",
    description: "Your perfect pack for everyday.",
    category: "Chambre",
    image: "/pouffe.jpg",
    stars: "5",
  },
];
export default data;
